# Generated by Django 4.1.4 on 2023-01-09 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('fullname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('confirmPassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('ingredients', models.CharField(max_length=300)),
                ('makeRecipe', models.CharField(max_length=300)),
                ('categories', models.CharField(choices=[('Tea', 'Tea'), ('Rice', 'Rice'), ('Pizza', 'Pizza'), ('Karhai', 'Karhai'), ('Cake', 'Cake'), ('Vegetable', 'Vegetable'), ('Salad', 'Salad')], max_length=150)),
                ('image', models.ImageField(blank=True, upload_to='my_picture')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skabapi.usermodel')),
            ],
        ),
    ]
