# Generated by Django 4.1.4 on 2023-01-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skabapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='image',
            field=models.ImageField(upload_to='my_picture'),
        ),
    ]
