# Generated by Django 4.1.4 on 2023-01-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skabapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('ingredients', models.CharField(max_length=300)),
                ('makeRecipe', models.CharField(max_length=300)),
                ('categories', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, upload_to='my_picture')),
            ],
        ),
    ]
