# Generated by Django 4.1.4 on 2023-02-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skabapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
