# Generated by Django 4.1.4 on 2023-03-08 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skabapi', '0002_recipemodel_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipemodel',
            name='Favorite',
        ),
    ]
