# Generated by Django 4.1.4 on 2023-01-09 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skabapi', '0002_alter_recipemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='skabapi.usermodel'),
        ),
    ]
