# Generated by Django 4.1.4 on 2023-01-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skabapi', '0002_recipemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='categories',
            field=models.CharField(choices=[('All', 'All'), ('Tea', 'Tea'), ('Biryani', 'Biryani'), ('Karhai', 'Karhai'), ('Cakes', 'Cakes'), ('Vegetables', 'Vegetables'), ('Salad', 'Salad')], max_length=150),
        ),
    ]
