# Generated by Django 4.1.4 on 2023-03-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skabapi', '0003_remove_recipemodel_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='Favorite',
            field=models.BooleanField(default=False),
        ),
    ]
