# Generated by Django 4.1.4 on 2023-01-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skabapi', '0003_alter_recipemodel_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipemodel',
            old_name='user',
            new_name='username',
        ),
    ]
