# Generated by Django 4.1.4 on 2023-03-08 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skabapi', '0004_recipemodel_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipemodel',
            old_name='Favorite',
            new_name='favorite',
        ),
    ]
