# Generated by Django 4.1.4 on 2023-01-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skabapi', '0004_rename_user_recipemodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='categories',
            field=models.CharField(choices=[('Tea', 'Tea'), ('Rice', 'Rice'), ('Pizza', 'Pizza'), ('Karhai', 'Karhai'), ('Cake', 'Cake'), ('Vegetable', 'Vegetable'), ('Salad', 'Salad')], max_length=150),
        ),
    ]
